server:
  port: 8888
#  ssl:
#    key-store: /home/user1/Desktop/clientkeystore
#    key-store-password: 123456
#    key-password: 123456
#    key-alias: client
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menus?useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: user1
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto : validate
    generate-ddl: false
    show-sql: false
    database: MYSQL
security:
  basic:
    enabled: true
  user:
    name: user1
    password: user1
  require-ssl: false
#logging:
#  level:
#    org:
#      springframework: DEBUG
#      springframework:
#        web: DEBUG
#        security: DEBUG
#      hibernate: DEBUG
