package com.sitisimenu.models;

// Generated Nov 30, 2014 12:14:31 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Menus generated by hbm2java
 */
@Entity
@Table(name = "menus", uniqueConstraints = @UniqueConstraint(columnNames = {
		"institution", "meal_day", "meal_type" }))
public class Menu {

	private Long id;
	private String institution;
	private Date mealDay;
	private String mealType;
	private String mainDishes;
	private String sideDishes;

	public Menu() {
	}

	public Menu(String institution, Date mealDay, String mealType,
			String mainDishes, String sideDishes) {
		this.institution = institution;
		this.mealDay = mealDay;
		this.mealType = mealType;
		this.mainDishes = mainDishes;
		this.sideDishes = sideDishes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "institution", nullable = false)
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "meal_day", nullable = false, length = 10)
	public Date getMealDay() {
		return this.mealDay;
	}

	public void setMealDay(Date mealDay) {
		this.mealDay = mealDay;
	}

	@Column(name = "meal_type", nullable = false)
	public String getMealType() {
		return this.mealType;
	}

	public void setMealType(String mealType) {
		this.mealType = mealType;
	}

	@Column(name = "main_dishes", nullable = false, length = 1023)
	public String getMainDishes() {
		return this.mainDishes;
	}

	public void setMainDishes(String mainDishes) {
		this.mainDishes = mainDishes;
	}

	@Column(name = "side_dishes", nullable = false, length = 1023)
	public String getSideDishes() {
		return this.sideDishes;
	}

	public void setSideDishes(String sideDishes) {
		this.sideDishes = sideDishes;
	}

}
